apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smart-rag.fullname" . }}-gateway
  labels:
    {{- include "smart-rag.labels" . | nindent 4 }}
    component: gateway
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "smart-rag.labels" . | nindent 6 }}
      component: gateway
  template:
    metadata:
      labels:
        {{- include "smart-rag.labels" . | nindent 8 }}
        component: gateway
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          ports:
            - containerPort: 443
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: config
              mountPath: /usr/share/nginx/html/no-cert.html
              subPath: no-cert.html
            - name: certs
              mountPath: /etc/nginx/certs
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "smart-rag.fullname" . }}-gateway-conf
        - name: certs
          secret:
            # You must create this secret manually or via external process
            secretName: gateway-certs