apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smart-rag.fullname" . }}-frontend
  labels:
    {{- include "smart-rag.labels" . | nindent 4 }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "smart-rag.labels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      labels:
        {{- include "smart-rag.labels" . | nindent 8 }}
        component: frontend
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: {{ .Values.frontend.env.viteApiUrl }}
            - name: VITE_TEST_MODE
              value: "False"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}